image:
  repository: cgr.dev/chainguard/opentelemetry-collector-contrib
  tag: latest
mode: deployment

resources:
  limits:
    memory: 200Mi

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true
  kubernetesAttributes:
    enabled: true

securityContext:
  runAsUser: 0
  runAsGroup: 0

config:
  exporters:
    googlecloud:
      log:
        default_log_name: opentelemetry.io/collector-exported-log
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
  processors:
    batch: {}
    # attributes:
    #   actions:
    #     - key: service.name
    #       value: bigquery-telemetry
    #       action: insert
    #     - key: gcp.project.id
    #       value: YOUR_PROJECT_ID
    #       action: insert
    memory_limiter:
      check_interval: 1s
      limit_percentage: 65
      spike_limit_percentage: 20
    resourcedetection:
      detectors: [gcp]
      timeout: 10s
  receivers:
    otlp:
      tls:
        insecure: true
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
      retry_on_failure:
        enabled: true
      initial_interval: 5s
      max_interval: 30s
    prometheus:
      config:
        scrape_configs:
        - job_name: bigquery_metrics
          metrics_path: /v1/projects/YOUR_PROJECT_ID/locations/global/prometheus
          authorization:
            credentials_file: /path/to/service-account-key.json
          static_configs:
            - targets: ["monitoring.googleapis.com"]
          scrape_interval: 60s
          metric_relabel_configs:
            - source_labels: [__name__]
              regex: "^bigquery_.*"
              action: keep
  service:
    telemetry:
      metrics:
        address: ${env:MY_POD_IP}:8888
    extensions:
      - health_check
    pipelines:
      logs:
        exporters:
          - googlecloud 
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      metrics:
        exporters:
          - googlecloud 
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - prometheus
      # traces:
      #   exporters:
      #     - googlecloud 
      #   processors:
      #     - memory_limiter
      #     - batch
      #   receivers:
      #     - otlp